name: 'Even Action1'
description: 'Greet someone and record the time'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  who-to-greet: # id of input
    description: 'who to greet'
    required: true
    default: 'xxx'
outputs:
  time:
    description: 'The time we greeted you'
runs:
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}
  using: 'composite'
  steps:
    - name: Run Script
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
        $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.who-to-greet }}
