name: Hello Action
on: [push]

jobs:
  hello_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello action step
      id: hello
      uses: songyanping/even-action1@master
      with:
        who-to-greet: 'Even'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
